// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGRsqWZJoj1-F0-wRfaKjv5FF41jE3oHw',
    appId: '1:309206159732:web:bc753c548e7c4b3d8a5c21',
    messagingSenderId: '309206159732',
    projectId: 'layla-da76e',
    authDomain: 'layla-da76e.firebaseapp.com',
    storageBucket: 'layla-da76e.firebasestorage.app',
    measurementId: 'G-E0CYXMFFYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1PAl4jpsZ9wiuBs4SR245GYlD5Bynn-o',
    appId: '1:309206159732:android:b8a776c33d346def8a5c21',
    messagingSenderId: '309206159732',
    projectId: 'layla-da76e',
    storageBucket: 'layla-da76e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm2cF7hCh2ZgWiw4vRvikfBlqVc_5UU3U',
    appId: '1:309206159732:ios:1eb6a8d90e510b488a5c21',
    messagingSenderId: '309206159732',
    projectId: 'layla-da76e',
    storageBucket: 'layla-da76e.firebasestorage.app',
    iosBundleId: 'com.example.layla',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm2cF7hCh2ZgWiw4vRvikfBlqVc_5UU3U',
    appId: '1:309206159732:ios:1eb6a8d90e510b488a5c21',
    messagingSenderId: '309206159732',
    projectId: 'layla-da76e',
    storageBucket: 'layla-da76e.firebasestorage.app',
    iosBundleId: 'com.example.layla',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGRsqWZJoj1-F0-wRfaKjv5FF41jE3oHw',
    appId: '1:309206159732:web:0d2435b9acfbe3508a5c21',
    messagingSenderId: '309206159732',
    projectId: 'layla-da76e',
    authDomain: 'layla-da76e.firebaseapp.com',
    storageBucket: 'layla-da76e.firebasestorage.app',
    measurementId: 'G-0Q2HJ1YXD3',
  );
}
